### ISSUE TITLE
TODO - MVP

### ISSUE THREAD

**Issue by DTHutton** [DTHutton/project_one_JMD#2]
# Characters
- [ ] character names
- [ ] character portraits
- [ ] assign attack and hp values
- [ ] generate attack button

# Stages
- [ ] setup API call to generate stages randomly
- [ ] transition effect for stage load

# Interactions
- [ ] hp drops on hit
- [ ] death animation that removes losing character
